version: "3.9"

services:
  web:
    build:
      context: .
      target: dev   # Use dev stage in Dockerfile
    container_name: flask_web
    command: flask run --host=0.0.0.0 --reload --extra-files /app/templates
    env_file: .env.dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app  # Code changes reflected immediately
      - ./templates:/app/templates
      - ./static:/app/static
    networks:
      - flask_network

  db:
    image: postgres:15
    container_name: flask_db
    restart: unless-stopped
    env_file: .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_network

volumes:
  postgres_data:

networks:
  flask_network:
