services:
  postgres:
    image: postgres:15
    container_name: db-test
    env_file: 
      - .env.test
    ports: ["5433:5432"]
    volumes:
      - pgtestdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 0.0.0.0"]
      interval: 2s
      timeout: 5s
      retries: 10

  app:
    
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: app-test
    env_file:
      - .env.test
    environment:
      - TESTING=1
      - PYTHONPATH=/app
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ./:/app:cached
    command: ["./ci/run-tests.sh"]   # run-tests.sh should wait for DB then run tests

volumes:
  pgtestdata:
