version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: flaskapp:dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi     # Point to the mounted folder
      - FLASK_ENV=development

    volumes:
      - .:/app    
    command: flask run --host=0.0.0.0  --reload
