version: "3.9"
services:
  app:
    build:
      context: .
      target: prod   # Use multi-stage prod target in Dockerfile 	
      dockerfile: Dockerfile
      
    image: flask-devops-portfolio:latest
    ports:
      - "8000:8000"  # Expose production port
    environment:
      - FLASK_APP=wsgi
    healthcheck:
      test: CMD ["gunicorn", "--check-config"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env.prod
