version: "3.9"
services:
  web:
    build:
      context: .
      target: prod   # Use multi-stage prod target in Dockerfile 	
      dockerfile: Dockerfile
      
    image: flaskapp:prod
    ports:
      - "8000:8000"  # Expose production port
    environment:
      - FLASK_APP=wsgi
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
