version: "3.9"

services:
  app:
    build:
      context: .
      target: dev   # Use dev stage in Dockerfile
      dockerfile: Dockerfile.dev
    image: flask-devops-portfolio:dev
    container_name: flask_app
    entrypoint: ["/app/entrypoint.sh"]                    #["/bin/sh", "-c", "/app/entrypoint.sh"]
    env_file: .env.dev
    environment:
      #- APP_ENV=development
      - MIGRATE_ON_STARTUP=true
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app  # Code changes reflected immediately
      - ./app/templates:/app/templates
      - ./app/static:/app/static
    networks:
      - flask_network

  db:
    image: postgres:15
    container_name: flask_db
    restart: unless-stopped
    env_file: .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_network

volumes:
  postgres_data:

networks:
  flask_network:
