"""Increase password_hash length

Revision ID: 394b9460c6c0
Revises: 3e239b0281ed
Create Date: 2025-08-31 15:49:51.792507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394b9460c6c0'
down_revision = '3e239b0281ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
