name: Flask CI/CD with GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
          APP_CONFIG: "testing" # Use testing config for SQLite
        
        steps:
            # Step 1: Checkout code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            # Step 3: Install dependencies
            - name: Install dependencies    
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
                export PYTHONPATH=$PWD
                pip install pytest
                
            # Step 4: Run tests
            - name: Run tests
              run: |
                export PYTHONPATH=$PWD  
                pytest
             
            # Step 5: Login to GHCR
            - name: Log in to GHCR
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GHCR_PAT }}


            # Step 6: Build and push Docker image with SHA and latest tags
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: |
                    ghcr.io/${{ github.repository_owner }}/flaskapp:latest
                    ghcr.io/${{ github.repository_owner }}/flaskapp:${{ github.sha }}


            # Step 7: Delete older images to save space (keep only the latest 2)
            - name: Delete old images
              uses: actions/delete-package-versions@v5
              with:
                package-name: 'flaskapp'
                package-type: 'container'
                min-versions-to-keep: 2
                num-old-versions-to-delete: 10  # Delete up to 10 old versions
                delete-only-pre-release-versions: false
                delete-only-untagged-versions: false
                ignore-versions: latest
                token: ${{ secrets.GHCR_PAT }}
