name: Generate Project Snapshot

on:
  push:
    branches: [main]           # Or other branches you want auto-snapshot
  pull_request:
    branches: [main]           # Run on PR merges into main

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv flask_venv
          # Use bash activation depending on OS
          if [ -f "flask_venv/bin/activate" ]; then
            source flask_venv/bin/activate
          else 
            source flask_venv/Scripts/activate
          fi
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Snapshot Generator
      - name: Run Snapshot Generator
        run: |
          # Use bash activation depending on OS
          if [ -f "flask_venv/bin/activate" ]; then
            source flask_venv/bin/activate
          else 
            source flask_venv/Scripts/activate
          fi
          python tools/snapshot_generator.py

      - name: Run Flake8 Linting
        run: |
          source flask_venv/bin/activate
          flake8 app tests

      - name: Run Pytest
        run: |
          source flask_venv/bin/activate
          pytest tests --maxfail=1 --disable-warnings -q

      # Step 5: Commit & Push PROJECT_SNAPSHOT.md
      - name: Commit and Push Snapshot
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add PROJECT_SNAPSHOT.md
          git commit -m "Update project snapshot [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

